# Generated by Django 4.2 on 2024-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID в телеграмме'),
        ),
    ]
