# Generated by Django 4.2 on 2024-08-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
    ]
