# Generated by Django 4.2 on 2024-08-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
