# Generated by Django 4.2 on 2024-08-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
    ]
