# Generated by Django 4.2 on 2024-09-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_course_owner_alter_lesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего изменения'),
        ),
    ]
